### ISSUE TITLE
Error in github actions

### ISSUE THREAD

**Issue by mzl-md** [moshensky/pdf-visual-diff#4]
When running in github actions, I get an error `Error: Command failed: gm convert: Coder did not return an image (this is a bug, please report it!) (/home/runner/work/pdf-visual-diff/pdf-visual-diff/src/test-data/two-page.pdf) [No such file or directory].`.

I can't reproduce this on my Mac or in an Ubuntu virtual machine.

How to reproduce: See https://github.com/moshensky/pdf-visual-diff/pull/5

Failed run: https://github.com/mzl-md/pdf-visual-diff/runs/1041915157?check_suite_focus=true

Full error:
```sh
  10) pdfToImages()
       should convert two page pdf to two images:
     Error: Command failed: gm convert: Coder did not return an image (this is a bug, please report it!) (/home/runner/work/pdf-visual-diff/pdf-visual-diff/src/test-data/two-page.pdf) [No such file or directory].

      at ChildProcess.onExit (node_modules/gm/lib/command.js:301:17)
      at maybeClose (internal/child_process.js:1021:16)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
```

Github action yml:
```yml
name: Pull Request CI/CD
on:
  pull_request:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:

jobs:
  primary:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install GraphicsMagick for tests
        run: |
          sudo add-apt-repository ppa:rwky/graphicsmagick
          sudo apt-get update
          sudo apt-get install graphicsmagick
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm run test
      - name: Run lint
        run: npm run lint
```
